[app]
name = "Battery Meter"
category = "Apps"

[entry]

[metadata]
author = "Matt Emerick-Law"
license = "MIT"
url = "https://github.com/emericklaw/tildagon-app-battery-meter/"
description = "Shows detailed information about the battery percentage, voltage levels and charging state."
version = "0.2.0"
