name: Create Release

on:
  push:
    paths:
      - 'tildagon.toml'
      - '.github/workflows/release.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      # - name: Get version
      #   id: get_version
      #   run: |
      #       {
      #         echo 'VERSION<<EOF'
      #         $(python -c "import toml; print(toml.load('tildagon.toml')['metadata']['version'])")
      #         echo EOF
      #       } >> "$GITHUB_ENV"

      # - name: Print version
      #   id: print_version
      #   run: |
      #     printf 'Version: %s\n' "$VERSION"
          
      - name: Get changes
        id: get_changes
        run: |
            {
              echo 'CHANGES<<EOF'
              $(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s")
              echo EOF
            } >> "$GITHUB_ENV"

      - name: Print changes
        id: print_changes
        run: |
          printf 'Changes:\n%s\n' "$CHANGES"
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body: |
            Changes:
            ${{ steps.get_changes.outputs.CHANGES }}
          draft: false
          prerelease: false
