name: Create Release

on:
  push:
    paths:
      - 'tildagon.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Get version
        id: get_version
        run: |
            echo "version=$(python -c \"import toml; print(toml.load('tildagon.toml')['metadata']['version'])\")" >> $GITHUB_VERSION

      - name: Get commits
        id: get_commits
        run: |
          echo "commits=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:\"- %s\")" >> $GITHUB_CHANGES

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        with:
          tag_name: v$GITHUB_VERSION
          release_name: v$GITHUB_VERSION
          body: |
            Changes:
            $GITHUB_CHANGES
          draft: false
          prerelease: false
